[package]
name = "clipboard-viewer"
version = "0.1.0"
authors = ["Sergey Demenok <sergey.demenok@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
crossclip = "0.7.0"
